import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider afterSignInUrl="/" afterSignUpUrl="/onboarding">
      <html lang="ja">
        <body>
          <SignedIn>
          {/* ログイン中に表示されるブロック */}
          <UserButton />
          </SignedIn>
          <SignedOut>
          {/* ログアウト中に表示されるブロック */}
          <SignInButton />
          <SignUpButton />
          </SignedOut>
          <div>
            {children}
          </div>
          <a href={process.env.NEXT_PUBLIC_CLERK_USER_PROFILE as string} target="_blank">
            アカウント設定
          </a>
        </body>
      </html>
    </ClerkProvider>
  )
}
